/**
 * Fetches all countries from REST Countries API and builds a fully
 * German-translated JSON. German country names come from `translations.deu.common`.
 * Run: bun run scripts/translateCountries.ts
 * Output: scripts/countries_de.json
 */

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

// ── Region / Subregion ────────────────────────────────────────────────────────

const REGION_DE: Record<string, string> = {
  'Africa': 'Afrika',
  'Americas': 'Amerika',
  'Asia': 'Asien',
  'Europe': 'Europa',
  'Oceania': 'Ozeanien',
  'Antarctic': 'Antarktis',
}

const SUBREGION_DE: Record<string, string> = {
  'Western Africa': 'Westafrika',
  'Eastern Africa': 'Ostafrika',
  'Northern Africa': 'Nordafrika',
  'Southern Africa': 'Südafrika',
  'Middle Africa': 'Zentralafrika',
  'South America': 'Südamerika',
  'North America': 'Nordamerika',
  'Central America': 'Mittelamerika',
  'Caribbean': 'Karibik',
  'Eastern Asia': 'Ostasien',
  'Western Asia': 'Westasien',
  'Southern Asia': 'Südasien',
  'South-Eastern Asia': 'Südostasien',
  'Central Asia': 'Zentralasien',
  'Western Europe': 'Westeuropa',
  'Eastern Europe': 'Osteuropa',
  'Northern Europe': 'Nordeuropa',
  'Southern Europe': 'Südeuropa',
  'Southeast Europe': 'Südosteuropa',
  'Australia and New Zealand': 'Australien und Neuseeland',
  'Melanesia': 'Melanesien',
  'Micronesia': 'Mikronesien',
  'Polynesia': 'Polynesien',
}

// ── Languages ─────────────────────────────────────────────────────────────────

const LANG_DE: Record<string, string> = {
  'Afrikaans': 'Afrikaans',
  'Albanian': 'Albanisch',
  'Amharic': 'Amharisch',
  'Arabic': 'Arabisch',
  'Armenian': 'Armenisch',
  'Azerbaijani': 'Aserbaidschanisch',
  'Basque': 'Baskisch',
  'Belarusian': 'Belarussisch',
  'Bengali': 'Bengalisch',
  'Bosnian': 'Bosnisch',
  'Bulgarian': 'Bulgarisch',
  'Burmese': 'Birmanisch',
  'Catalan': 'Katalanisch',
  'Chinese': 'Chinesisch',
  'Croatian': 'Kroatisch',
  'Czech': 'Tschechisch',
  'Danish': 'Dänisch',
  'Dutch': 'Niederländisch',
  'Dzongkha': 'Dzongkha',
  'English': 'Englisch',
  'Estonian': 'Estnisch',
  'Faroese': 'Färöisch',
  'Fijian': 'Fidschianisch',
  'Finnish': 'Finnisch',
  'French': 'Französisch',
  'Galician': 'Galizisch',
  'Georgian': 'Georgisch',
  'German': 'Deutsch',
  'Greek': 'Griechisch',
  'Guaraní': 'Guaraní',
  'Gujarati': 'Gujarati',
  'Haitian Creole': 'Haitianisches Kreolisch',
  'Hausa': 'Hausa',
  'Hebrew': 'Hebräisch',
  'Hindi': 'Hindi',
  'Hungarian': 'Ungarisch',
  'Icelandic': 'Isländisch',
  'Indonesian': 'Indonesisch',
  'Irish': 'Irisch',
  'Italian': 'Italienisch',
  'Japanese': 'Japanisch',
  'Kannada': 'Kannada',
  'Kazakh': 'Kasachisch',
  'Khmer': 'Khmer',
  'Kinyarwanda': 'Kinyarwanda',
  'Korean': 'Koreanisch',
  'Kurdish': 'Kurdisch',
  'Kyrgyz': 'Kirgisisch',
  'Lao': 'Laotisch',
  'Latin': 'Latein',
  'Latvian': 'Lettisch',
  'Lingala': 'Lingala',
  'Lithuanian': 'Litauisch',
  'Luxembourgish': 'Luxemburgisch',
  'Macedonian': 'Mazedonisch',
  'Malagasy': 'Madagassisch',
  'Malay': 'Malaiisch',
  'Maltese': 'Maltesisch',
  'Māori': 'Māori',
  'Marathi': 'Marathi',
  'Moldovan': 'Moldauisch',
  'Mongolian': 'Mongolisch',
  'Montenegrin': 'Montenegrinisch',
  'Nepali': 'Nepalesisch',
  'Norwegian': 'Norwegisch',
  'Nynorsk': 'Nynorsk',
  'Papiamento': 'Papiamento',
  'Pashto': 'Paschtunisch',
  'Persian': 'Persisch',
  'Polish': 'Polnisch',
  'Portuguese': 'Portugiesisch',
  'Punjabi': 'Punjabi',
  'Romanian': 'Rumänisch',
  'Romansh': 'Rätoromanisch',
  'Russian': 'Russisch',
  'Samoan': 'Samoanisch',
  'Serbian': 'Serbisch',
  'Shona': 'Shona',
  'Sindhi': 'Sindhi',
  'Sinhala': 'Singhalesisch',
  'Slovak': 'Slowakisch',
  'Slovene': 'Slowenisch',
  'Somali': 'Somali',
  'Spanish': 'Spanisch',
  'Swahili': 'Suaheli',
  'Swati': 'Swati',
  'Swedish': 'Schwedisch',
  'Tagalog': 'Filipino',
  'Tajik': 'Tadschikisch',
  'Tamil': 'Tamilisch',
  'Telugu': 'Telugu',
  'Thai': 'Thailändisch',
  'Tibetan': 'Tibetisch',
  'Tigrinya': 'Tigrinya',
  'Tok Pisin': 'Tok Pisin',
  'Tongan': 'Tongaisch',
  'Turkish': 'Türkisch',
  'Turkmen': 'Turkmenisch',
  'Ukrainian': 'Ukrainisch',
  'Urdu': 'Urdu',
  'Uzbek': 'Usbekisch',
  'Vietnamese': 'Vietnamesisch',
  'Welsh': 'Walisisch',
  'Wolof': 'Wolof',
  'Xhosa': 'Xhosa',
  'Yoruba': 'Yoruba',
  'Zulu': 'Zulu',
  // French variants
  'French Creole': 'Französisches Kreolisch',
  'Antillean Creole': 'Antillianisches Kreolisch',
}

// ── Currencies ────────────────────────────────────────────────────────────────

const CURRENCY_DE: Record<string, string> = {
  'Euro': 'Euro',
  'United States dollar': 'US-Dollar',
  'Pound sterling': 'Britisches Pfund',
  'Swiss franc': 'Schweizer Franken',
  'Japanese yen': 'Japanischer Yen',
  'Chinese yuan': 'Chinesischer Yuan',
  'Indian rupee': 'Indische Rupie',
  'Russian ruble': 'Russischer Rubel',
  'Canadian dollar': 'Kanadischer Dollar',
  'Australian dollar': 'Australischer Dollar',
  'New Zealand dollar': 'Neuseeländischer Dollar',
  'South Korean won': 'Südkoreanischer Won',
  'Hong Kong dollar': 'Hongkong-Dollar',
  'Singapore dollar': 'Singapur-Dollar',
  'Swedish krona': 'Schwedische Krone',
  'Norwegian krone': 'Norwegische Krone',
  'Danish krone': 'Dänische Krone',
  'Czech koruna': 'Tschechische Krone',
  'Hungarian forint': 'Ungarischer Forint',
  'Polish złoty': 'Polnischer Zloty',
  'Romanian leu': 'Rumänischer Leu',
  'Bulgarian lev': 'Bulgarischer Lew',
  'Croatian kuna': 'Kroatische Kuna',
  'Turkish lira': 'Türkische Lira',
  'Israeli new shekel': 'Israelischer Neuer Schekel',
  'Saudi riyal': 'Saudischer Riyal',
  'UAE dirham': 'Emiratischer Dirham',
  'Qatari riyal': 'Katarischer Riyal',
  'Kuwaiti dinar': 'Kuwaitischer Dinar',
  'Bahraini dinar': 'Bahrainischer Dinar',
  'Omani rial': 'Omanischer Rial',
  'Jordanian dinar': 'Jordanischer Dinar',
  'Egyptian pound': 'Ägyptisches Pfund',
  'South African rand': 'Südafrikanischer Rand',
  'Nigerian naira': 'Nigerianische Naira',
  'Kenyan shilling': 'Kenianischer Schilling',
  'Ghanaian cedi': 'Ghanaischer Cedi',
  'Ethiopian birr': 'Äthiopischer Birr',
  'Moroccan dirham': 'Marokkanischer Dirham',
  'Tunisian dinar': 'Tunesischer Dinar',
  'Algerian dinar': 'Algerischer Dinar',
  'Argentine peso': 'Argentinischer Peso',
  'Brazilian real': 'Brasilianischer Real',
  'Mexican peso': 'Mexikanischer Peso',
  'Chilean peso': 'Chilenischer Peso',
  'Colombian peso': 'Kolumbianischer Peso',
  'Peruvian sol': 'Peruanischer Sol',
  'Venezuelan bolívar soberano': 'Venezolanischer Bolívar',
  'Uruguayan peso': 'Uruguayischer Peso',
  'Bolivian boliviano': 'Bolivianischer Boliviano',
  'Paraguayan guaraní': 'Paraguayischer Guaraní',
  'Cuban peso': 'Kubanischer Peso',
  'Thai baht': 'Thailändischer Baht',
  'Vietnamese đồng': 'Vietnamesischer Dong',
  'Indonesian rupiah': 'Indonesische Rupiah',
  'Malaysian ringgit': 'Malaysischer Ringgit',
  'Philippine peso': 'Philippinischer Peso',
  'Pakistani rupee': 'Pakistanische Rupie',
  'Bangladeshi taka': 'Bangladeschische Taka',
  'Sri Lankan rupee': 'Sri-lankische Rupie',
  'Nepalese rupee': 'Nepalesische Rupie',
  'Ukrainian hryvnia': 'Ukrainische Hrywnja',
  'Serbian dinar': 'Serbischer Dinar',
  'Albanian lek': 'Albanischer Lek',
  'Bosnian convertible mark': 'Bosnische Konvertible Mark',
  'Macedonian denar': 'Mazedonischer Denar',
  'Icelandic króna': 'Isländische Krone',
  'Georgian lari': 'Georgischer Lari',
  'Armenian dram': 'Armenischer Dram',
  'Azerbaijani manat': 'Aserbaidschanischer Manat',
  'Kazakhstani tenge': 'Kasachischer Tenge',
  'Uzbekistani soʻm': 'Usbekischer Sum',
  'Kyrgystani som': 'Kirgisischer Som',
  'Tajikistani somoni': 'Tadschikischer Somoni',
  'Turkmenistan manat': 'Turkmenischer Manat',
  'Mongolian tögrög': 'Mongolischer Tögrög',
  'Myanmar kyat': 'Myanmarischer Kyat',
  'Cambodian riel': 'Kambodschanischer Riel',
  'Laotian kip': 'Laotischer Kip',
  'New Taiwan dollar': 'Neuer Taiwanesischer Dollar',
  'Maldivian rufiyaa': 'Maledivische Rufiyaa',
  'Afghan afghani': 'Afghaner Afghani',
  'Iranian rial': 'Iranischer Rial',
  'Iraqi dinar': 'Irakischer Dinar',
  'Syrian pound': 'Syrisches Pfund',
  'Lebanese pound': 'Libanesisches Pfund',
  'Libyan dinar': 'Libyscher Dinar',
  'Sudanese pound': 'Sudanesisches Pfund',
  'Somali shilling': 'Somalischer Schilling',
  'Ugandan shilling': 'Ugandischer Schilling',
  'Tanzanian shilling': 'Tansanischer Schilling',
  'Rwandan franc': 'Ruandischer Franc',
  'Burundian franc': 'Burundischer Franc',
  'Congolese franc': 'Kongolesischer Franc',
  'Zambian kwacha': 'Sambischer Kwacha',
  'Malawian kwacha': 'Malawischer Kwacha',
  'Zimbabwean dollar': 'Simbabwischer Dollar',
  'Botswana pula': 'Botswanischer Pula',
  'Namibian dollar': 'Namibischer Dollar',
  'Mozambican metical': 'Mosambikanischer Metical',
  'Angolan kwanza': 'Angolanischer Kwanza',
  'Senegalese franc': 'Senegalesischer Franc',
  'West African CFA franc': 'Westafrikanischer CFA-Franc',
  'Central African CFA franc': 'Zentralafrikanischer CFA-Franc',
  'CFP franc': 'CFP-Franc',
  'East Caribbean dollar': 'Ostkaribischer Dollar',
  'Haitian gourde': 'Haitianische Gourde',
  'Jamaican dollar': 'Jamaikanischer Dollar',
  'Trinidad and Tobago dollar': 'Trinidad-und-Tobago-Dollar',
  'Barbadian dollar': 'Barbadischer Dollar',
  'Belize dollar': 'Belizisches Dollar',
  'Guatemalan quetzal': 'Guatemaltekischer Quetzal',
  'Honduran lempira': 'Honduranische Lempira',
  'Salvadoran colón': 'Salvadorianischer Colón',
  'Nicaraguan córdoba': 'Nicaraguanischer Córdoba',
  'Costa Rican colón': 'Costa-ricanischer Colón',
  'Panamanian balboa': 'Panamaischer Balboa',
  'Dominican peso': 'Dominikanischer Peso',
  'Papua New Guinean kina': 'Papua-Neuguineanische Kina',
  'Fijian dollar': 'Fidschianischer Dollar',
  'Solomon Islands dollar': 'Salomonischer Dollar',
  'Vanuatu vatu': 'Vanuatischer Vatu',
  'Tongan paʻanga': 'Tongaischer Paʻanga',
  'Samoan tālā': 'Samoanischer Tālā',
  'Liberian dollar': 'Liberianischer Dollar',
  'Sierra Leonean leone': 'Sierra-leonischer Leone',
  'Guinean franc': 'Guineischer Franc',
  'Cape Verdean escudo': 'Kapverdischer Escudo',
  'São Tomé and Príncipe dobra': 'São-toméischer Dobra',
  'Mauritanian ouguiya': 'Mauretanische Ouguiya',
  'Gambian dalasi': 'Gambischer Dalasi',
  'Mauritius rupee': 'Mauritische Rupie',
  'Seychellois rupee': 'Seychellische Rupie',
  'Comorian franc': 'Komorische Franc',
  'Djiboutian franc': 'Dschibutischer Franc',
  'Eritrean nakfa': 'Eritreischer Nakfa',
  'Malagasy ariary': 'Madagassischer Ariary',
  'Lesotho loti': 'Lesothischer Loti',
  'Swazi lilangeni': 'Swasiländischer Lilangeni',
  'Bhutanese ngultrum': 'Bhutanischer Ngultrum',
  'Brunei dollar': 'Bruneischer Dollar',
  'Timor-Leste centavo': 'Timoresischer Centavo',
  'North Korean won': 'Nordkoreanischer Won',
  'Cuban convertible peso': 'Kubanischer konvertibler Peso',
  'Belarusian ruble': 'Weißrussischer Rubel',
  'Moldovan leu': 'Moldauischer Leu',
  'Kosovo euro': 'Euro',
  'Transnistrian ruble': 'Transnistrischer Rubel',
}

// ── Capitals (German names) ───────────────────────────────────────────────────

const CAPITAL_DE: Record<string, string> = {
  'Vienna': 'Wien',
  'Rome': 'Rom',
  'Athens': 'Athen',
  'Beijing': 'Peking',
  'Moscow': 'Moskau',
  'Lisbon': 'Lissabon',
  'Brussels': 'Brüssel',
  'Copenhagen': 'Kopenhagen',
  'Warsaw': 'Warschau',
  'Prague': 'Prag',
  'Bucharest': 'Bukarest',
  'Belgrade': 'Belgrad',
  'Kyiv': 'Kiew',
  'Cairo': 'Kairo',
  'Algiers': 'Algier',
  'Tripoli': 'Tripolis',
  'Khartoum': 'Khartum',
  'Addis Ababa': 'Addis Abeba',
  'Tehran': 'Teheran',
  'Baghdad': 'Bagdad',
  'Riyadh': 'Riad',
  'Tokyo': 'Tokio',
  'Mexico City': 'Mexiko-Stadt',
  'New Delhi': 'Neu-Delhi',
  'Havana': 'Havanna',
  'Singapore': 'Singapur',
  'Seoul': 'Seoul',
  'Tbilisi': 'Tiflis',
  'Yerevan': 'Eriwan',
  'Bern': 'Bern',
  'The Hague': 'Den Haag',
  'Luxembourg': 'Luxemburg',
  'Nicosia': 'Nikosia',
  'Valletta': 'Valletta',
  'Vilnius': 'Wilna',
  'Riga': 'Riga',
  'Tallinn': 'Tallinn',
  'Sarajevo': 'Sarajevo',
  'Skopje': 'Skopje',
  'Podgorica': 'Podgorica',
  'Tirana': 'Tirana',
  'Pristina': 'Pristina',
  'Chisinau': 'Chișinău',
  'Minsk': 'Minsk',
  'Baku': 'Baku',
  'Ankara': 'Ankara',
  'Tunis': 'Tunis',
  'Rabat': 'Rabat',
  'Dakar': 'Dakar',
  'Nairobi': 'Nairobi',
  'Accra': 'Akkra',
  'Cape Town': 'Kapstadt',
  'Islamabad': 'Islamabad',
  'Kabul': 'Kabul',
  'Bangkok': 'Bangkok',
  'Jakarta': 'Jakarta',
  'Manila': 'Manila',
  'Kuala Lumpur': 'Kuala Lumpur',
  'Canberra': 'Canberra',
  'Wellington': 'Wellington',
  'Ottawa': 'Ottawa',
  'Brasília': 'Brasília',
  'Buenos Aires': 'Buenos Aires',
  'Lima': 'Lima',
  'Bogotá': 'Bogotá',
  'Santiago': 'Santiago de Chile',
  'Caracas': 'Caracas',
  'Montevideo': 'Montevideo',
  'Asunción': 'Asunción',
  'La Paz': 'La Paz',
  'Quito': 'Quito',
  'Georgetown': 'Georgetown',
  'Paramaribo': 'Paramaribo',
  'Cayenne': 'Cayenne',
  'Nassau': 'Nassau',
  'Kingston': 'Kingston',
  'Port-au-Prince': 'Port-au-Prince',
  'Santo Domingo': 'Santo Domingo',
  'San Juan': 'San Juan',
  'Bridgetown': 'Bridgetown',
  'Port of Spain': 'Port of Spain',
  'Castries': 'Castries',
  'Kingstown': 'Kingstown',
  'Roseau': 'Roseau',
  'Saint George\'s': 'Saint George\'s',
  'Basseterre': 'Basseterre',
  "Saint John's": "Saint John's",
  'Belmopan': 'Belmopan',
  'Guatemala City': 'Guatemala-Stadt',
  'Tegucigalpa': 'Tegucigalpa',
  'San Salvador': 'San Salvador',
  'Managua': 'Managua',
  'San José': 'San José',
  'Panama City': 'Panama-Stadt',
  'Havana': 'Havanna',
  'Abuja': 'Abuja',
  'Pretoria': 'Pretoria',
  'Harare': 'Harare',
  'Lusaka': 'Lusaka',
  'Lilongwe': 'Lilongwe',
  'Maputo': 'Maputo',
  'Antananarivo': 'Antananarivo',
  'Kampala': 'Kampala',
  'Dar es Salaam': 'Daressalam',
  'Dodoma': 'Dodoma',
  'Kigali': 'Kigali',
  'Bujumbura': 'Bujumbura',
  'Kinshasa': 'Kinshasa',
  'Brazzaville': 'Brazzaville',
  'Luanda': 'Luanda',
  'Libreville': 'Libreville',
  'Malabo': 'Malabo',
  'Yaoundé': 'Jaunde',
  'Bangui': 'Bangui',
  'Ndjamena': 'N\'Djamena',
  'Niamey': 'Niamey',
  'Ouagadougou': 'Ouagadougou',
  'Bamako': 'Bamako',
  'Conakry': 'Conakry',
  'Freetown': 'Freetown',
  'Monrovia': 'Monrovia',
  'Yamoussoukro': 'Yamoussoukro',
  'Abidjan': 'Abidjan',
  'Accra': 'Akkra',
  'Lomé': 'Lomé',
  'Porto-Novo': 'Porto-Novo',
  'Cotonou': 'Cotonou',
  'Lagos': 'Lagos',
  'Bissau': 'Bissau',
  'Banjul': 'Banjul',
  'Nouakchott': 'Nouakchott',
  'Praia': 'Praia',
  'São Tomé': 'São Tomé',
  'Malabo': 'Malabo',
  'Djibouti': 'Dschibuti',
  'Mogadishu': 'Mogadischu',
  'Asmara': 'Asmara',
  'Gaborone': 'Gaborone',
  'Windhoek': 'Windhoek',
  'Maseru': 'Maseru',
  'Mbabane': 'Mbabane',
  'Moroni': 'Moroni',
  'Victoria': 'Victoria',
  'Port Louis': 'Port Louis',
  'Antananarivo': 'Antananarivo',
  'Kathmandu': 'Kathmandu',
  'Thimphu': 'Thimphu',
  'Dhaka': 'Dhaka',
  'Colombo': 'Colombo',
  'Sri Jayawardenepura Kotte': 'Sri Jayawardenepura Kotte',
  'Male': 'Malé',
  'Taipei': 'Taipeh',
  'Ulaanbaatar': 'Ulaanbaatar',
  'Pyongyang': 'Pjöngjang',
  'Phnom Penh': 'Phnom Penh',
  'Vientiane': 'Vientiane',
  'Naypyidaw': 'Naypyidaw',
  'Bandar Seri Begawan': 'Bandar Seri Begawan',
  'Dili': 'Dili',
  'Port Moresby': 'Port Moresby',
  'Honiara': 'Honiara',
  'Port Vila': 'Port Vila',
  'Suva': 'Suva',
  'Nuku\'alofa': 'Nuku\'alofa',
  'Apia': 'Apia',
  "Funafuti": 'Funafuti',
  'Tarawa': 'Tarawa',
  'Majuro': 'Majuro',
  'Palikir': 'Palikir',
  'Ngerulmud': 'Ngerulmud',
  'Yaren': 'Yaren',
  'Avarua': 'Avarua',
  'Alofi': 'Alofi',
  'Hagåtña': 'Hagåtña',
  'Saipan': 'Saipan',
  'Pago Pago': 'Pago Pago',
  'Papeete': 'Papeete',
  'Nouméa': 'Nouméa',
  'Mata-Utu': 'Mata-Utu',
  'Adamstown': 'Adamstown',
  'Flying Fish Cove': 'Flying Fish Cove',
  'West Island': 'West Island',
  'Edinburgh of the Seven Seas': 'Edinburgh of the Seven Seas',
  'Georgetown': 'Georgetown',
  'Jamestown': 'Jamestown',
  'Cockburn Town': 'Cockburn Town',
  'Road Town': 'Road Town',
  "Charlotte Amalie": 'Charlotte Amalie',
  'The Valley': 'The Valley',
  'Marigot': 'Marigot',
  'Philipsburg': 'Philipsburg',
  'Gustavia': 'Gustavia',
  'Brades': 'Brades',
  'Plymouth': 'Plymouth',
  'Hamilton': 'Hamilton',
  'Douglas': 'Douglas',
  'Saint Helier': 'Saint Helier',
  'Saint Peter Port': 'Saint Peter Port',
  'Vaduz': 'Vaduz',
  'Andorra la Vella': 'Andorra la Vella',
  'San Marino': 'San Marino',
  'Vatican City': 'Vatikanstadt',
  'Monaco': 'Monaco',
  'Longyearbyen': 'Longyearbyen',
  'Nuuk': 'Nuuk',
  'Tórshavn': 'Tórshavn',
  'Reykjavik': 'Reykjavík',
  'Helsinki': 'Helsinki',
  'Oslo': 'Oslo',
  'Stockholm': 'Stockholm',
  'London': 'London',
  'Dublin': 'Dublin',
  'Madrid': 'Madrid',
  'Paris': 'Paris',
  'Berlin': 'Berlin',
  'Amsterdam': 'Amsterdam',
  'Brussels': 'Brüssel',
  'Bern': 'Bern',
  'Budapest': 'Budapest',
  'Warsaw': 'Warschau',
  'Sofia': 'Sofia',
  'Ljubljana': 'Ljubljana',
  'Zagreb': 'Zagreb',
  'Bratislava': 'Bratislava',
  'Belgrade': 'Belgrad',
  'Valletta': 'Valletta',
  'Nicosia': 'Nikosia',
  'Skopje': 'Skopje',
  'Tirana': 'Tirana',
  'Chisinau': 'Chișinău',
  'Minsk': 'Minsk',
  'Vilnius': 'Wilna',
  'Riga': 'Riga',
  'Tallinn': 'Tallinn',
  'Kyiv': 'Kiew',
  'Baku': 'Baku',
  'Tbilisi': 'Tiflis',
  'Yerevan': 'Eriwan',
  'Ankara': 'Ankara',
  'Nicosia': 'Nikosia',
  'Abu Dhabi': 'Abu Dhabi',
  'Doha': 'Doha',
  'Kuwait City': 'Kuwait-Stadt',
  'Manama': 'Manama',
  'Muscat': 'Maskat',
  'Sanaa': 'Sanaa',
  'Amman': 'Amman',
  'Beirut': 'Beirut',
  'Damascus': 'Damaskus',
  'Jerusalem': 'Jerusalem',
  'Ramallah': 'Ramallah',
  'Ashgabat': 'Aschgabat',
  'Tashkent': 'Taschkent',
  'Bishkek': 'Bischkek',
  'Dushanbe': 'Duschanbe',
  'Nur-Sultan': 'Nur-Sultan',
  'Astana': 'Astana',
}

// ── Main ──────────────────────────────────────────────────────────────────────

interface RestCountry {
  cca2: string
  name: { common: string }
  translations?: Record<string, { common?: string; official?: string }>
  capital?: string[]
  region: string
  subregion?: string
  population: number
  languages?: Record<string, string>
  currencies?: Record<string, { name: string; symbol: string }>
  flags: { svg: string; png: string }
}

console.log('Fetching country data...')
// max 10 fields per REST Countries API limit — area comes from local DB
const res = await fetch(
  'https://restcountries.com/v3.1/all?fields=cca2,name,translations,capital,region,subregion,population,languages,currencies,flags'
)
const data = (await res.json()) as RestCountry[]
console.log(`Got ${data.length} countries`)

const output: Record<string, object> = {}

for (const c of data) {
  const id = c.cca2.toLowerCase()

  const name_de = c.translations?.['deu']?.common ?? c.name.common
  const name_en = c.name.common

  const capitalRaw = c.capital?.[0] ?? null
  const capital = capitalRaw ? (CAPITAL_DE[capitalRaw] ?? capitalRaw) : null

  const region = REGION_DE[c.region] ?? c.region
  const subregion = c.subregion ? (SUBREGION_DE[c.subregion] ?? c.subregion) : null

  const languages = c.languages
    ? Object.values(c.languages).map((l) => LANG_DE[l] ?? l)
    : []

  const currencies = c.currencies
    ? Object.values(c.currencies).map((v) => {
        const name = CURRENCY_DE[v.name] ?? v.name
        return `${name} (${v.symbol})`
      })
    : []

  output[id] = {
    id,
    name_en,
    name_de,
    capital,
    region,
    subregion,
    flag_svg: c.flags.svg,
    flag_png: c.flags.png,
    population: c.population,
    languages,
    currencies,
  }
}

// Sort by country id alphabetically
const sorted = Object.fromEntries(Object.entries(output).sort(([a], [b]) => a.localeCompare(b)))

const outPath = join(import.meta.dir, 'countries_de.json')
writeFileSync(outPath, JSON.stringify(sorted, null, 2), 'utf-8')
console.log(`✓ Saved to ${outPath}`)
